[package]
name = "plasma-cash-token"
version = "0.1.0"
authors = ["Zatoichi Labs <admin@zatoichi-labs.com"]
edition = "2018"

[dependencies]
bitvec = "0.14.0"

[dev-dependencies]
ethabi = "8.0.0"
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1" }
ethereum-types = "0.6.0"
keccak-hash = "0.2.0"
